export type Person = {
  id: number;
  name: string;
  age: number;
  email: string;
  department: string;
  joinedAt: string;
  role: string;
  salary: number;
  location: string;
  status: "active" | "inactive" | "on-leave";
};

export const data: Person[] = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    email: "john@example.com",
    department: "Engineering",
    joinedAt: "2022-01-15",
    role: "Senior Engineer",
    salary: 95000,
    location: "New York",
    status: "active",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 25,
    email: "jane@example.com",
    department: "Design",
    joinedAt: "2023-03-20",
    role: "UI Designer",
    salary: 72000,
    location: "San Francisco",
    status: "active",
  },
  {
    id: 3,
    name: "Bob Johnson",
    age: 35,
    email: "bob@example.com",
    department: "Marketing",
    joinedAt: "2021-08-10",
    role: "Marketing Manager",
    salary: 88000,
    location: "Chicago",
    status: "active",
  },
  {
    id: 4,
    name: "Alice Williams",
    age: 28,
    email: "alice@example.com",
    department: "Engineering",
    joinedAt: "2022-11-05",
    role: "Frontend Developer",
    salary: 82000,
    location: "Austin",
    status: "active",
  },
  {
    id: 5,
    name: "Charlie Brown",
    age: 42,
    email: "charlie@example.com",
    department: "Sales",
    joinedAt: "2020-04-22",
    role: "Sales Director",
    salary: 110000,
    location: "Boston",
    status: "active",
  },
  {
    id: 6,
    name: "Diana Miller",
    age: 31,
    email: "diana@example.com",
    department: "Engineering",
    joinedAt: "2021-06-12",
    role: "Backend Developer",
    salary: 85000,
    location: "Seattle",
    status: "active",
  },
  {
    id: 7,
    name: "Edward Davis",
    age: 29,
    email: "edward@example.com",
    department: "HR",
    joinedAt: "2023-01-08",
    role: "HR Specialist",
    salary: 62000,
    location: "Denver",
    status: "active",
  },
  {
    id: 8,
    name: "Fiona Garcia",
    age: 34,
    email: "fiona@example.com",
    department: "Design",
    joinedAt: "2020-09-15",
    role: "Lead Designer",
    salary: 92000,
    location: "Los Angeles",
    status: "on-leave",
  },
  {
    id: 9,
    name: "George Martinez",
    age: 27,
    email: "george@example.com",
    department: "Marketing",
    joinedAt: "2022-07-20",
    role: "Content Strategist",
    salary: 68000,
    location: "Miami",
    status: "active",
  },
  {
    id: 10,
    name: "Hannah Rodriguez",
    age: 38,
    email: "hannah@example.com",
    department: "Engineering",
    joinedAt: "2019-11-30",
    role: "Tech Lead",
    salary: 125000,
    location: "New York",
    status: "active",
  },
  {
    id: 11,
    name: "Ian Wilson",
    age: 45,
    email: "ian@example.com",
    department: "Sales",
    joinedAt: "2018-03-05",
    role: "VP of Sales",
    salary: 145000,
    location: "Chicago",
    status: "active",
  },
  {
    id: 12,
    name: "Julia Anderson",
    age: 26,
    email: "julia@example.com",
    department: "Design",
    joinedAt: "2023-05-18",
    role: "Junior Designer",
    salary: 58000,
    location: "Portland",
    status: "active",
  },
  {
    id: 13,
    name: "Kevin Thomas",
    age: 33,
    email: "kevin@example.com",
    department: "Engineering",
    joinedAt: "2021-02-14",
    role: "DevOps Engineer",
    salary: 98000,
    location: "Austin",
    status: "active",
  },
  {
    id: 14,
    name: "Laura Taylor",
    age: 29,
    email: "laura@example.com",
    department: "HR",
    joinedAt: "2022-08-22",
    role: "Recruiter",
    salary: 65000,
    location: "San Francisco",
    status: "active",
  },
  {
    id: 15,
    name: "Michael Moore",
    age: 41,
    email: "michael@example.com",
    department: "Marketing",
    joinedAt: "2019-04-10",
    role: "Marketing Director",
    salary: 115000,
    location: "Boston",
    status: "active",
  },
  {
    id: 16,
    name: "Nancy Jackson",
    age: 36,
    email: "nancy@example.com",
    department: "Engineering",
    joinedAt: "2020-12-01",
    role: "Staff Engineer",
    salary: 135000,
    location: "Seattle",
    status: "active",
  },
  {
    id: 17,
    name: "Oscar White",
    age: 24,
    email: "oscar@example.com",
    department: "Design",
    joinedAt: "2024-01-10",
    role: "Design Intern",
    salary: 45000,
    location: "New York",
    status: "active",
  },
  {
    id: 18,
    name: "Patricia Harris",
    age: 32,
    email: "patricia@example.com",
    department: "Sales",
    joinedAt: "2021-09-25",
    role: "Account Executive",
    salary: 78000,
    location: "Dallas",
    status: "inactive",
  },
  {
    id: 19,
    name: "Quinn Martin",
    age: 28,
    email: "quinn@example.com",
    department: "Engineering",
    joinedAt: "2022-04-17",
    role: "Full Stack Developer",
    salary: 88000,
    location: "Denver",
    status: "active",
  },
  {
    id: 20,
    name: "Rachel Thompson",
    age: 37,
    email: "rachel@example.com",
    department: "HR",
    joinedAt: "2019-07-08",
    role: "HR Manager",
    salary: 95000,
    location: "Chicago",
    status: "active",
  },
  {
    id: 21,
    name: "Steven Clark",
    age: 44,
    email: "steven@example.com",
    department: "Marketing",
    joinedAt: "2018-10-20",
    role: "CMO",
    salary: 165000,
    location: "San Francisco",
    status: "active",
  },
  {
    id: 22,
    name: "Tina Lewis",
    age: 30,
    email: "tina@example.com",
    department: "Design",
    joinedAt: "2021-12-12",
    role: "UX Researcher",
    salary: 82000,
    location: "Austin",
    status: "active",
  },
  {
    id: 23,
    name: "Ulysses Robinson",
    age: 39,
    email: "ulysses@example.com",
    department: "Engineering",
    joinedAt: "2020-02-28",
    role: "Principal Engineer",
    salary: 155000,
    location: "New York",
    status: "active",
  },
  {
    id: 24,
    name: "Vera Walker",
    age: 27,
    email: "vera@example.com",
    department: "Sales",
    joinedAt: "2023-06-05",
    role: "Sales Rep",
    salary: 55000,
    location: "Phoenix",
    status: "active",
  },
  {
    id: 25,
    name: "William Hall",
    age: 35,
    email: "william@example.com",
    department: "Engineering",
    joinedAt: "2020-08-18",
    role: "Security Engineer",
    salary: 105000,
    location: "Seattle",
    status: "active",
  },
  {
    id: 26,
    name: "Xena Young",
    age: 31,
    email: "xena@example.com",
    department: "HR",
    joinedAt: "2022-03-30",
    role: "Training Coordinator",
    salary: 58000,
    location: "Atlanta",
    status: "on-leave",
  },
  {
    id: 27,
    name: "Yusuf King",
    age: 43,
    email: "yusuf@example.com",
    department: "Marketing",
    joinedAt: "2019-01-22",
    role: "Brand Manager",
    salary: 98000,
    location: "Los Angeles",
    status: "active",
  },
  {
    id: 28,
    name: "Zoe Wright",
    age: 26,
    email: "zoe@example.com",
    department: "Design",
    joinedAt: "2023-09-14",
    role: "Product Designer",
    salary: 75000,
    location: "Portland",
    status: "active",
  },
  {
    id: 29,
    name: "Aaron Scott",
    age: 34,
    email: "aaron@example.com",
    department: "Engineering",
    joinedAt: "2021-05-07",
    role: "Mobile Developer",
    salary: 92000,
    location: "Miami",
    status: "active",
  },
  {
    id: 30,
    name: "Bella Green",
    age: 29,
    email: "bella@example.com",
    department: "Sales",
    joinedAt: "2022-10-11",
    role: "Business Development",
    salary: 72000,
    location: "Dallas",
    status: "active",
  },
  {
    id: 31,
    name: "Carlos Adams",
    age: 40,
    email: "carlos@example.com",
    department: "Engineering",
    joinedAt: "2019-06-19",
    role: "Engineering Manager",
    salary: 140000,
    location: "Austin",
    status: "active",
  },
  {
    id: 32,
    name: "Daisy Baker",
    age: 23,
    email: "daisy@example.com",
    department: "Design",
    joinedAt: "2024-02-01",
    role: "Visual Designer",
    salary: 52000,
    location: "San Francisco",
    status: "active",
  },
  {
    id: 33,
    name: "Ethan Nelson",
    age: 36,
    email: "ethan@example.com",
    department: "HR",
    joinedAt: "2020-11-24",
    role: "Compensation Analyst",
    salary: 78000,
    location: "Chicago",
    status: "active",
  },
  {
    id: 34,
    name: "Faith Carter",
    age: 28,
    email: "faith@example.com",
    department: "Marketing",
    joinedAt: "2022-06-08",
    role: "Social Media Manager",
    salary: 65000,
    location: "New York",
    status: "inactive",
  },
  {
    id: 35,
    name: "Grant Mitchell",
    age: 47,
    email: "grant@example.com",
    department: "Engineering",
    joinedAt: "2017-08-15",
    role: "CTO",
    salary: 200000,
    location: "San Francisco",
    status: "active",
  },
];
